### ISSUE TITLE
About input dataset

### ISSUE THREAD

**Issue by aidevveloper** [astaka-pe/DeepMeshPrior#1]
Hi nice job!
Can you recommend how to prepare input datasets for this type of implementation?
I am interested in your opinion. ^--^
Thank you in advance!

**Comment by astaka-pe** [comment]
Hi @Harry-KIT,
in general, these triangle mesh data (`.obj` files) are obtained with optical scanners.
If you don't have a scanner on hand, you can use the [distributed scanned models](http://graphics.stanford.edu/data/3Dscanrep/).
You can also obtain 3D models from previous works such as [GNF](https://github.com/bldeng/GuidedDenoising), [DNF-Net](https://github.com/nini-lxz/DNF-Net) or [GCN-Denoiser](https://github.com/Jhonve/GCN-Denoiser).
Finally, I suggest you check [our newer work on mesh denoising](https://github.com/astaka-pe/Dual-DMP).

**Comment by aidevveloper** [comment]
Hi @astaka-pe,
Ok, I will follow it.
Thank you for quick reply.
