### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by saqibnaziir** [astaka-pe/DeepMeshPrior#2]
Thanks for your work, I have installed all the dependencies but when I try to run 
"python completion.py -i datasets/c_input/dragon"

I get the following error:
"Segmentation fault". 
Can you please clarify how I can resolve it?

**Comment by astaka-pe** [comment]
@saqibnaziir
Could you give me more details of the error message?

**Comment by astaka-pe** [comment]
@saqibnaziir Because the original environment no longer exists, we are unable to verify it. We have added a Dockerfile with updated dependencies and confirmed that it works. Please try using it.
https://github.com/astaka-pe/DeepMeshPrior?tab=readme-ov-file#installation
